coverage:
  status:
    project:
      default:
        # Use the same thresholds as vitest
        target: 97%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 96%
        threshold: 1%

  ignore:
    - "dist/**/*"
    - "coverage/**/*"
    - "node_modules/**/*"
    - "src/cli.ts"
    - "tests/**/*"
    - "*.config.*"
    - "*.md"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

flags:
  unittests:
    paths:
      - src/

github_checks:
  annotations: true 